export interface HowToGuide {
  slug: string
  title: string
  description: string
  toolSlug: string
  toolName: string
  category: string
  steps: { name: string; text: string }[]
  faqs: { question: string; answer: string }[]
}

export const HOW_TO_CATEGORIES: { id: string; name: string }[] = [
  { id: 'developer', name: 'Developer Tools' },
  { id: 'image', name: 'Image Tools' },
  { id: 'text', name: 'Text Tools' },
  { id: 'seo', name: 'SEO Tools' },
  { id: 'color', name: 'Color Tools' },
  { id: 'css', name: 'CSS Tools' },
  { id: 'financial', name: 'Financial Calculators' },
  { id: 'converters', name: 'Converters' },
  { id: 'encoders', name: 'Encoders & Decoders' },
  { id: 'generators', name: 'Generators' },
]

export const HOW_TO_GUIDES: HowToGuide[] = [
  // ── Developer Tools ─────────────────────────────────────────────────────
  {
    slug: 'format-json',
    title: 'How to Format JSON Online',
    description: 'Learn how to format, beautify, and validate JSON data online for free. Indent messy JSON in seconds.',
    toolSlug: 'json-formatter',
    toolName: 'JSON Formatter & Validator',
    category: 'developer',
    steps: [
      { name: 'Open the JSON Formatter', text: 'Navigate to the JSON Formatter tool on UtilsNow. No signup or installation is needed.' },
      { name: 'Paste your JSON', text: 'Copy your raw or minified JSON data and paste it into the input area on the left side of the tool.' },
      { name: 'Choose indentation', text: 'Select your preferred indentation level (2 spaces, 4 spaces, or tabs) from the settings.' },
      { name: 'View the formatted output', text: 'The tool instantly formats your JSON with proper indentation, syntax highlighting, and validates the structure. Any errors are highlighted with line numbers.' },
      { name: 'Copy or download', text: 'Click the Copy button to copy the formatted JSON to your clipboard, or download it as a .json file.' },
    ],
    faqs: [
      { question: 'Is the JSON formatter free to use?', answer: 'Yes, the JSON formatter is completely free. There are no limits on usage, file size, or formatting operations.' },
      { question: 'Does my JSON data get uploaded to a server?', answer: 'No. All formatting happens directly in your browser. Your data never leaves your device, ensuring complete privacy.' },
      { question: 'Can I validate JSON while formatting?', answer: 'Yes, the tool automatically validates your JSON as it formats. Any syntax errors are highlighted with descriptive error messages and line numbers.' },
    ],
  },
  {
    slug: 'convert-csv-to-json',
    title: 'How to Convert CSV to JSON',
    description: 'Convert CSV files and data to JSON format online. Free tool with instant conversion and no file uploads.',
    toolSlug: 'csv-to-json',
    toolName: 'CSV to JSON Converter',
    category: 'developer',
    steps: [
      { name: 'Open the CSV to JSON tool', text: 'Go to the CSV to JSON converter on UtilsNow. It works directly in your browser with no signup required.' },
      { name: 'Paste or upload your CSV', text: 'Paste your CSV data into the input area. The first row should contain column headers that will become JSON keys.' },
      { name: 'Configure options', text: 'Choose your delimiter (comma, tab, semicolon) and select whether to output an array of objects or nested JSON.' },
      { name: 'Convert instantly', text: 'The tool automatically converts your CSV to properly structured JSON in real time as you type or paste.' },
      { name: 'Copy the JSON output', text: 'Click Copy to grab the JSON output, or download it as a .json file for use in your application.' },
    ],
    faqs: [
      { question: 'What CSV delimiters are supported?', answer: 'The tool supports commas, tabs, semicolons, and pipe characters as delimiters. It also auto-detects the delimiter in most cases.' },
      { question: 'Can I convert large CSV files?', answer: 'Yes, since all processing happens in your browser, you can convert CSV files of any size limited only by your device memory.' },
      { question: 'Does it handle quoted fields and special characters?', answer: 'Yes, the converter properly handles quoted fields, escaped quotes, newlines within fields, and Unicode characters.' },
    ],
  },
  {
    slug: 'validate-json',
    title: 'How to Validate JSON Online',
    description: 'Validate JSON data for syntax errors instantly. Free online JSON validator with detailed error messages.',
    toolSlug: 'json-validator',
    toolName: 'JSON Validator',
    category: 'developer',
    steps: [
      { name: 'Open the JSON Validator', text: 'Navigate to the JSON Validator tool on UtilsNow. It runs entirely in your browser for privacy.' },
      { name: 'Paste your JSON data', text: 'Copy your JSON string and paste it into the input area. The tool accepts any size of JSON data.' },
      { name: 'Check validation results', text: 'The tool instantly validates your JSON and shows either a success message or a detailed error with the line number and position of the issue.' },
      { name: 'Fix any errors', text: 'If errors are found, the tool highlights the exact location of the problem and suggests how to fix common issues like missing commas or brackets.' },
      { name: 'Copy the valid JSON', text: 'Once your JSON is valid, copy the cleaned version or download it as a file.' },
    ],
    faqs: [
      { question: 'What JSON errors can the validator detect?', answer: 'It detects missing commas, unclosed brackets, trailing commas, invalid escape sequences, duplicate keys, and all other JSON syntax violations.' },
      { question: 'Can I validate JSON against a schema?', answer: 'The tool validates JSON syntax. For schema validation (JSON Schema), use the JSON Formatter which offers more advanced options.' },
      { question: 'Is there a size limit for validation?', answer: 'No. Since validation happens locally in your browser, there is no server-imposed size limit.' },
    ],
  },
  {
    slug: 'convert-json-to-yaml',
    title: 'How to Convert JSON to YAML',
    description: 'Convert JSON to YAML format online. Perfect for Kubernetes configs, Docker Compose files, and CI/CD pipelines.',
    toolSlug: 'json-to-yaml',
    toolName: 'JSON to YAML Converter',
    category: 'developer',
    steps: [
      { name: 'Open the JSON to YAML tool', text: 'Go to the JSON to YAML converter on UtilsNow. No installation or signup needed.' },
      { name: 'Paste your JSON', text: 'Copy your JSON data and paste it into the input field. The tool validates it first to ensure correct conversion.' },
      { name: 'Configure YAML options', text: 'Choose your preferred indentation level and flow style settings for the YAML output.' },
      { name: 'Get the YAML output', text: 'The tool instantly converts your JSON to clean, human-readable YAML format with proper indentation and structure.' },
      { name: 'Copy or download', text: 'Copy the YAML output to your clipboard or download it as a .yaml or .yml file.' },
    ],
    faqs: [
      { question: 'Why convert JSON to YAML?', answer: 'YAML is more human-readable than JSON and is the standard format for Kubernetes manifests, Docker Compose files, GitHub Actions workflows, and many other DevOps tools.' },
      { question: 'Does the conversion preserve data types?', answer: 'Yes, all JSON data types (strings, numbers, booleans, null, arrays, objects) are correctly mapped to their YAML equivalents.' },
      { question: 'Can I convert YAML back to JSON?', answer: 'Yes, UtilsNow also offers a YAML to JSON converter tool for the reverse conversion.' },
    ],
  },
  {
    slug: 'convert-json-to-typescript',
    title: 'How to Convert JSON to TypeScript Types',
    description: 'Generate TypeScript interfaces and types from JSON data automatically. Save time writing type definitions.',
    toolSlug: 'json-to-typescript',
    toolName: 'JSON to TypeScript',
    category: 'developer',
    steps: [
      { name: 'Open the JSON to TypeScript tool', text: 'Navigate to the JSON to TypeScript converter on UtilsNow. Works instantly in your browser.' },
      { name: 'Paste your JSON data', text: 'Paste a sample JSON response (e.g. from an API) into the input area. This provides the structure for type generation.' },
      { name: 'Configure options', text: 'Choose between interfaces or type aliases, set the root type name, and configure optional properties if needed.' },
      { name: 'Generate TypeScript types', text: 'The tool analyzes your JSON structure and generates accurate TypeScript interfaces with proper types for all fields, including nested objects and arrays.' },
      { name: 'Copy to your project', text: 'Copy the generated TypeScript code and paste it into your project source file.' },
    ],
    faqs: [
      { question: 'Does it handle nested JSON objects?', answer: 'Yes, the tool recursively generates separate interfaces for nested objects, creating clean and reusable type definitions.' },
      { question: 'Can it generate types from API responses?', answer: 'Yes, just paste a sample API response and the tool will generate complete TypeScript types matching the response structure.' },
      { question: 'Does it support arrays and optional fields?', answer: 'Yes, arrays are typed correctly (e.g., string[], number[]) and you can configure fields as optional with the ? modifier.' },
    ],
  },
  {
    slug: 'format-sql',
    title: 'How to Format SQL Queries Online',
    description: 'Format and beautify SQL queries online for free. Supports MySQL, PostgreSQL, and standard SQL syntax.',
    toolSlug: 'sql-formatter',
    toolName: 'SQL Formatter',
    category: 'developer',
    steps: [
      { name: 'Open the SQL Formatter', text: 'Go to the SQL Formatter tool on UtilsNow. It works in your browser with no installation needed.' },
      { name: 'Paste your SQL query', text: 'Copy your messy or minified SQL query and paste it into the input area.' },
      { name: 'Select SQL dialect', text: 'Choose your SQL dialect (Standard SQL, MySQL, PostgreSQL, SQLite, etc.) for accurate keyword formatting.' },
      { name: 'Format the query', text: 'The tool formats your SQL with proper indentation, keyword capitalization, and line breaks for optimal readability.' },
      { name: 'Copy the formatted SQL', text: 'Copy the beautifully formatted SQL query to use in your database client, documentation, or code.' },
    ],
    faqs: [
      { question: 'Which SQL dialects are supported?', answer: 'The formatter supports Standard SQL, MySQL, PostgreSQL, SQLite, MariaDB, and T-SQL syntax variations.' },
      { question: 'Does it uppercase SQL keywords?', answer: 'Yes, by default SQL keywords (SELECT, FROM, WHERE, etc.) are uppercased for readability. This can be configured.' },
      { question: 'Can it format complex queries with subqueries?', answer: 'Yes, the tool handles complex queries including subqueries, CTEs, JOINs, and nested expressions with proper indentation.' },
    ],
  },
  {
    slug: 'test-regex',
    title: 'How to Test Regular Expressions Online',
    description: 'Test and debug regex patterns online with real-time matching, capturing groups, and explanations.',
    toolSlug: 'regex-tester',
    toolName: 'Regex Tester',
    category: 'developer',
    steps: [
      { name: 'Open the Regex Tester', text: 'Navigate to the Regex Tester tool on UtilsNow. It provides a real-time testing environment.' },
      { name: 'Enter your regex pattern', text: 'Type or paste your regular expression pattern in the pattern input field at the top.' },
      { name: 'Set flags', text: 'Choose regex flags like global (g), case-insensitive (i), multiline (m), or dotAll (s) as needed.' },
      { name: 'Add test strings', text: 'Paste or type the text you want to test against in the test string area. Matches are highlighted in real time.' },
      { name: 'Analyze matches', text: 'View all matches, capturing groups, and their positions. The tool shows exactly what each group captures.' },
    ],
    faqs: [
      { question: 'Which regex flavors are supported?', answer: 'The tool uses JavaScript regex syntax, which is compatible with most programming languages including Python, Java, and PHP for common patterns.' },
      { question: 'Can I see capturing groups?', answer: 'Yes, the tool displays all capturing groups with their indices and captured values for each match.' },
      { question: 'Does it explain the regex pattern?', answer: 'Yes, the tool provides a breakdown of what each part of your regex pattern does, making it easier to understand and debug.' },
    ],
  },
  {
    slug: 'decode-jwt',
    title: 'How to Decode JWT Tokens',
    description: 'Decode and inspect JWT (JSON Web Tokens) online. View the header, payload, and verify token structure.',
    toolSlug: 'jwt-decoder',
    toolName: 'JWT Decoder',
    category: 'developer',
    steps: [
      { name: 'Open the JWT Decoder', text: 'Go to the JWT Decoder tool on UtilsNow. It decodes tokens entirely in your browser for security.' },
      { name: 'Paste your JWT token', text: 'Copy the JWT token from your application, API response, or authentication header and paste it into the input field.' },
      { name: 'View the decoded header', text: 'The tool displays the decoded header showing the algorithm (e.g., HS256, RS256) and token type.' },
      { name: 'Inspect the payload', text: 'View the decoded payload with all claims including iss, sub, exp, iat, and any custom claims in a readable format.' },
      { name: 'Check expiration', text: 'The tool shows whether the token is expired by comparing the exp claim against the current time.' },
    ],
    faqs: [
      { question: 'Is it safe to decode JWTs online?', answer: 'Yes, this tool decodes tokens entirely in your browser. Your JWT never leaves your device and is not sent to any server.' },
      { question: 'Can I verify JWT signatures?', answer: 'The tool decodes and displays the token structure. For full signature verification, you need the secret key or public key used to sign the token.' },
      { question: 'What JWT algorithms are supported?', answer: 'The decoder displays tokens signed with any algorithm (HS256, HS384, HS512, RS256, RS384, RS512, ES256, etc.) since it only decodes the base64 content.' },
    ],
  },

  // ── Image Tools ─────────────────────────────────────────────────────────
  {
    slug: 'generate-qr-code',
    title: 'How to Generate a QR Code',
    description: 'Create QR codes for URLs, text, WiFi, and more. Free QR code generator with customization options.',
    toolSlug: 'qr-code-generator',
    toolName: 'QR Code Generator',
    category: 'image',
    steps: [
      { name: 'Open the QR Code Generator', text: 'Navigate to the QR Code Generator tool on UtilsNow. No signup or payment required.' },
      { name: 'Enter your content', text: 'Type or paste the URL, text, phone number, email, or WiFi credentials you want to encode in the QR code.' },
      { name: 'Customize appearance', text: 'Choose colors, size, and error correction level. Higher error correction allows the QR code to be scanned even if partially damaged.' },
      { name: 'Preview the QR code', text: 'The QR code is generated in real time as you type. Test it with your phone camera to make sure it works.' },
      { name: 'Download the QR code', text: 'Download your QR code as a PNG or SVG image. SVG is best for print materials as it scales without quality loss.' },
    ],
    faqs: [
      { question: 'What content can I encode in a QR code?', answer: 'You can encode URLs, plain text, phone numbers, email addresses, WiFi network credentials, vCard contacts, and more.' },
      { question: 'What size should my QR code be?', answer: 'For print, use at least 300x300 pixels. For billboards or large signs, use SVG format which scales infinitely without quality loss.' },
      { question: 'Do QR codes expire?', answer: 'Static QR codes (like the ones generated here) never expire. The encoded data is embedded directly in the code pattern.' },
    ],
  },
  {
    slug: 'resize-image',
    title: 'How to Resize an Image Online',
    description: 'Resize images to exact dimensions online. Supports PNG, JPG, and WebP with quality controls.',
    toolSlug: 'image-resizer',
    toolName: 'Image Resizer',
    category: 'image',
    steps: [
      { name: 'Open the Image Resizer', text: 'Go to the Image Resizer tool on UtilsNow. All processing happens in your browser for privacy.' },
      { name: 'Upload your image', text: 'Drag and drop your image or click to browse. Supports PNG, JPG, WebP, and other common formats.' },
      { name: 'Set dimensions', text: 'Enter the desired width and height in pixels. Toggle "Maintain aspect ratio" to prevent distortion.' },
      { name: 'Choose output format', text: 'Select the output format (PNG, JPEG, or WebP) and adjust quality settings for the best file size vs quality balance.' },
      { name: 'Download the resized image', text: 'Click Download to save your resized image. The original image is never modified.' },
    ],
    faqs: [
      { question: 'Is there a file size limit?', answer: 'Since all processing happens in your browser, there is no upload limit. Very large images may take a moment to process depending on your device.' },
      { question: 'Does resizing reduce image quality?', answer: 'Enlarging images can reduce quality. Reducing size maintains quality. Use the quality slider to control the file size vs quality tradeoff.' },
      { question: 'Can I resize multiple images at once?', answer: 'Currently the tool processes one image at a time. Upload each image separately for the best results.' },
    ],
  },
  {
    slug: 'remove-image-background',
    title: 'How to Remove Image Background with AI',
    description: 'Remove backgrounds from images automatically using AI. Free tool with no signup required.',
    toolSlug: 'ai-bg-remover',
    toolName: 'AI Background Remover',
    category: 'image',
    steps: [
      { name: 'Open the AI Background Remover', text: 'Navigate to the AI Background Remover on UtilsNow. The AI model loads directly in your browser.' },
      { name: 'Upload your image', text: 'Drag and drop your photo or click to upload. The tool works best with clear subjects like people, products, or objects.' },
      { name: 'Wait for AI processing', text: 'The AI model analyzes your image and automatically detects the subject. This takes 5-15 seconds depending on image size and your device.' },
      { name: 'Review the result', text: 'The background is removed and replaced with a transparent or white background. Check the edges for accuracy.' },
      { name: 'Download the result', text: 'Download the image with transparent background as a PNG file. Use it for product photos, profile pictures, or design projects.' },
    ],
    faqs: [
      { question: 'Does the AI run on a server?', answer: 'No. The AI model runs entirely in your browser using WebAssembly. Your images are never uploaded to any server, ensuring complete privacy.' },
      { question: 'What image types work best?', answer: 'The AI works best with clear subjects against contrasting backgrounds. Product photos, portraits, and objects on simple backgrounds give the best results.' },
      { question: 'Can I choose a custom background color?', answer: 'The tool removes the background to transparency (PNG). You can then place the image on any background color using an image editor.' },
    ],
  },
  {
    slug: 'crop-image',
    title: 'How to Crop an Image Online',
    description: 'Crop images to custom dimensions or aspect ratios online. Free tool with preset sizes for social media.',
    toolSlug: 'image-cropper',
    toolName: 'Image Cropper',
    category: 'image',
    steps: [
      { name: 'Open the Image Cropper', text: 'Go to the Image Cropper tool on UtilsNow. It works in any browser with no installation needed.' },
      { name: 'Upload your image', text: 'Drag and drop your image or click to browse. Supports all major image formats.' },
      { name: 'Select crop area', text: 'Drag the crop handles to select the area you want to keep. Use preset aspect ratios (1:1, 16:9, 4:3) or set a custom ratio.' },
      { name: 'Adjust the selection', text: 'Move and resize the crop area until you have the exact framing you want. The preview shows the final result in real time.' },
      { name: 'Download the cropped image', text: 'Click Crop and download your perfectly cropped image in your preferred format.' },
    ],
    faqs: [
      { question: 'What aspect ratio presets are available?', answer: 'The tool includes presets for 1:1 (Instagram), 16:9 (YouTube), 4:3 (standard), 9:16 (Stories), and custom dimensions.' },
      { question: 'Can I crop to exact pixel dimensions?', answer: 'Yes, you can enter exact width and height values in pixels for precise cropping.' },
      { question: 'Does cropping reduce image quality?', answer: 'No, cropping only removes the unwanted portions. The remaining pixels retain their original quality.' },
    ],
  },
  {
    slug: 'convert-image-format',
    title: 'How to Convert Image Formats Online',
    description: 'Convert between PNG, JPG, WebP, GIF, and other image formats online. Free with no quality loss.',
    toolSlug: 'image-format-converter',
    toolName: 'Image Format Converter',
    category: 'image',
    steps: [
      { name: 'Open the Image Format Converter', text: 'Navigate to the Image Format Converter on UtilsNow. All conversion happens locally in your browser.' },
      { name: 'Upload your image', text: 'Drag and drop your image file or click to browse and select the file you want to convert.' },
      { name: 'Choose output format', text: 'Select the target format: PNG (lossless, transparent), JPG (photos, smaller), WebP (modern, efficient), or other supported formats.' },
      { name: 'Adjust quality settings', text: 'For lossy formats like JPG and WebP, use the quality slider to balance file size and image quality.' },
      { name: 'Download the converted image', text: 'Click Convert and download your image in the new format. The original file remains unchanged.' },
    ],
    faqs: [
      { question: 'Which image formats are supported?', answer: 'The tool supports PNG, JPG/JPEG, WebP, GIF, BMP, and ICO formats for conversion in any direction.' },
      { question: 'Is there quality loss when converting?', answer: 'Converting to lossless formats (PNG) preserves quality. Converting to lossy formats (JPG, WebP) may have slight quality reduction controlled by the quality slider.' },
      { question: 'Can I convert WebP to PNG?', answer: 'Yes, you can convert from any supported format to any other. WebP to PNG, PNG to JPG, JPG to WebP, and all other combinations are supported.' },
    ],
  },
  {
    slug: 'generate-favicon',
    title: 'How to Generate a Favicon for Your Website',
    description: 'Create favicons in all required sizes from a single image. Supports ICO, PNG, and SVG formats.',
    toolSlug: 'favicon-generator',
    toolName: 'Favicon Generator',
    category: 'image',
    steps: [
      { name: 'Open the Favicon Generator', text: 'Go to the Favicon Generator tool on UtilsNow. Generate all favicon sizes from one source image.' },
      { name: 'Upload your logo or icon', text: 'Upload a square image (ideally 512x512 pixels or larger) that represents your brand or website.' },
      { name: 'Preview the favicons', text: 'The tool generates previews in all standard sizes: 16x16, 32x32, 48x48, 180x180 (Apple Touch Icon), and 192x192.' },
      { name: 'Download the favicon package', text: 'Download all favicon sizes in a ZIP file, including the ICO file that contains multiple sizes.' },
      { name: 'Add to your website', text: 'Copy the provided HTML link tags and paste them into the <head> section of your website.' },
    ],
    faqs: [
      { question: 'What size should the source image be?', answer: 'Use a square image at least 512x512 pixels. Larger images produce better results when scaled down to smaller favicon sizes.' },
      { question: 'What favicon sizes do I need?', answer: 'Modern browsers need 16x16 (tabs), 32x32 (bookmarks), 180x180 (Apple Touch Icon), and 192x192 (Android). The ICO format bundles multiple sizes.' },
      { question: 'Do I need an ICO file?', answer: 'ICO files are recommended for maximum compatibility. They bundle multiple sizes into one file and are supported by all browsers including older ones.' },
    ],
  },

  // ── Text Tools ──────────────────────────────────────────────────────────
  {
    slug: 'count-words',
    title: 'How to Count Words in Text',
    description: 'Count words, characters, sentences, and paragraphs in any text online. Free word counter with reading time.',
    toolSlug: 'word-counter',
    toolName: 'Word Counter',
    category: 'text',
    steps: [
      { name: 'Open the Word Counter', text: 'Navigate to the Word Counter tool on UtilsNow. It provides instant statistics as you type.' },
      { name: 'Paste or type your text', text: 'Paste your article, essay, or any text into the input area. There is no character limit.' },
      { name: 'View word count', text: 'The tool instantly shows the total word count, updating in real time as you type or edit.' },
      { name: 'Check additional stats', text: 'View character count (with and without spaces), sentence count, paragraph count, and estimated reading time.' },
      { name: 'Use for your needs', text: 'Use the counts for meeting essay requirements, checking social media character limits, or estimating content length.' },
    ],
    faqs: [
      { question: 'How is reading time calculated?', answer: 'Reading time is based on an average reading speed of 200-250 words per minute, which is the standard for adult readers.' },
      { question: 'Does it count hyphenated words as one or two?', answer: 'Hyphenated words (like "well-known") are counted as one word, following standard English word counting conventions.' },
      { question: 'Can I count words in specific sections?', answer: 'Yes, simply select and paste the specific section you want to count. The tool counts whatever text is in the input area.' },
    ],
  },
  {
    slug: 'convert-text-case',
    title: 'How to Convert Text Case Online',
    description: 'Convert text to uppercase, lowercase, title case, sentence case, and more. Free case converter tool.',
    toolSlug: 'case-converter',
    toolName: 'Case Converter',
    category: 'text',
    steps: [
      { name: 'Open the Case Converter', text: 'Go to the Case Converter tool on UtilsNow. It supports multiple text case formats.' },
      { name: 'Paste your text', text: 'Copy and paste the text you want to convert into the input area.' },
      { name: 'Choose the case type', text: 'Select from UPPERCASE, lowercase, Title Case, Sentence case, camelCase, PascalCase, snake_case, or kebab-case.' },
      { name: 'View the converted text', text: 'The tool instantly converts your text to the selected case format in the output area.' },
      { name: 'Copy the result', text: 'Click Copy to copy the converted text to your clipboard for use in your documents or code.' },
    ],
    faqs: [
      { question: 'What is Title Case?', answer: 'Title Case capitalizes the first letter of each word. Most style guides exclude small words (a, an, the, and, etc.) unless they start the title.' },
      { question: 'What is the difference between camelCase and PascalCase?', answer: 'camelCase starts with a lowercase letter (myVariable), while PascalCase starts with an uppercase letter (MyVariable). Both capitalize subsequent words.' },
      { question: 'Can I convert code variable names?', answer: 'Yes, the tool supports developer cases like camelCase, PascalCase, snake_case, and kebab-case, perfect for renaming variables.' },
    ],
  },
  {
    slug: 'find-and-replace-text',
    title: 'How to Find and Replace Text Online',
    description: 'Find and replace text in bulk online. Supports regex, case-sensitive matching, and multiple replacements.',
    toolSlug: 'find-and-replace',
    toolName: 'Find & Replace',
    category: 'text',
    steps: [
      { name: 'Open Find & Replace', text: 'Navigate to the Find & Replace tool on UtilsNow. It handles bulk text replacements instantly.' },
      { name: 'Paste your text', text: 'Paste the text content where you want to make replacements.' },
      { name: 'Enter search and replace terms', text: 'Type the text to find in the Search field and the replacement text in the Replace field.' },
      { name: 'Configure options', text: 'Choose case-sensitive matching, whole word only, or enable regex mode for pattern-based replacements.' },
      { name: 'Apply and copy', text: 'Click Replace All to apply all replacements. Review the result and copy the modified text.' },
    ],
    faqs: [
      { question: 'Does it support regular expressions?', answer: 'Yes, you can enable regex mode to use regular expression patterns for advanced find and replace operations.' },
      { question: 'Can I do multiple replacements at once?', answer: 'Yes, you can chain multiple find-and-replace operations. Each replacement is applied to the result of the previous one.' },
      { question: 'Is the replacement case-sensitive by default?', answer: 'Yes, replacements are case-sensitive by default. You can toggle case-insensitive mode in the options.' },
    ],
  },
  {
    slug: 'remove-duplicate-lines',
    title: 'How to Remove Duplicate Lines from Text',
    description: 'Remove duplicate lines from text instantly. Keep unique lines with optional case-insensitive matching.',
    toolSlug: 'duplicate-line-remover',
    toolName: 'Duplicate Line Remover',
    category: 'text',
    steps: [
      { name: 'Open the Duplicate Line Remover', text: 'Go to the Duplicate Line Remover tool on UtilsNow. It works instantly in your browser.' },
      { name: 'Paste your text', text: 'Paste the text containing duplicate lines. This works great for lists, log files, CSV data, and more.' },
      { name: 'Configure options', text: 'Choose case-sensitive or case-insensitive comparison. Select whether to trim whitespace before comparing.' },
      { name: 'Remove duplicates', text: 'The tool instantly removes all duplicate lines, keeping only the first occurrence of each unique line.' },
      { name: 'Copy the result', text: 'Copy the deduplicated text. The tool also shows how many duplicate lines were removed.' },
    ],
    faqs: [
      { question: 'Does it preserve the original order?', answer: 'Yes, the tool preserves the order of lines and keeps the first occurrence of each duplicate.' },
      { question: 'Can it handle large text files?', answer: 'Yes, the tool processes text locally in your browser and can handle thousands of lines efficiently.' },
      { question: 'Does it remove blank lines too?', answer: 'Blank lines are treated as duplicates of each other. Enable the trim whitespace option to also catch lines with only spaces.' },
    ],
  },
  {
    slug: 'sort-text-lines',
    title: 'How to Sort Text Lines Alphabetically',
    description: 'Sort lines of text alphabetically, numerically, or by length online. Supports ascending and descending order.',
    toolSlug: 'text-sorter',
    toolName: 'Text Sorter',
    category: 'text',
    steps: [
      { name: 'Open the Text Sorter', text: 'Navigate to the Text Sorter tool on UtilsNow. Sort any list of lines instantly.' },
      { name: 'Paste your text', text: 'Paste the lines you want to sort. Each line will be sorted independently.' },
      { name: 'Choose sort method', text: 'Select alphabetical (A-Z), reverse alphabetical (Z-A), numerical, by line length, or random shuffle.' },
      { name: 'Apply sorting', text: 'The tool instantly sorts all lines according to your chosen method and displays the result.' },
      { name: 'Copy the sorted text', text: 'Copy the sorted lines to your clipboard for use in your documents or spreadsheets.' },
    ],
    faqs: [
      { question: 'Can I sort numbers?', answer: 'Yes, use numerical sort mode to sort numbers correctly (1, 2, 10, 20 instead of 1, 10, 2, 20 which happens with alphabetical sort).' },
      { question: 'Does it handle case-insensitive sorting?', answer: 'Yes, you can enable case-insensitive sorting so "apple" and "Apple" are treated equally for ordering purposes.' },
      { question: 'Can I sort a comma-separated list?', answer: 'The tool sorts by lines. Convert your comma-separated list to one item per line first, or use the list tools for comma-separated values.' },
    ],
  },

  // ── SEO Tools ───────────────────────────────────────────────────────────
  {
    slug: 'generate-meta-tags',
    title: 'How to Generate Meta Tags for SEO',
    description: 'Generate SEO meta tags for your website including title, description, Open Graph, and Twitter Card tags.',
    toolSlug: 'meta-tag-generator',
    toolName: 'Meta Tag Generator',
    category: 'seo',
    steps: [
      { name: 'Open the Meta Tag Generator', text: 'Navigate to the Meta Tag Generator on UtilsNow. It creates all essential meta tags for your pages.' },
      { name: 'Enter page details', text: 'Fill in your page title (50-60 characters), description (150-160 characters), and target keywords.' },
      { name: 'Configure Open Graph tags', text: 'Add Open Graph tags for Facebook and LinkedIn sharing. Enter your OG image URL, site name, and page type.' },
      { name: 'Set Twitter Card tags', text: 'Choose Twitter Card type (summary or large image) and enter your Twitter handle for attribution.' },
      { name: 'Copy the meta tags', text: 'Copy the generated HTML meta tags and paste them into the <head> section of your web page.' },
    ],
    faqs: [
      { question: 'What meta tags are essential for SEO?', answer: 'The essential meta tags are: title tag, meta description, viewport, charset, canonical URL, and Open Graph tags for social sharing.' },
      { question: 'What is the ideal title tag length?', answer: 'Keep titles between 50-60 characters. Google typically displays the first 50-60 characters in search results.' },
      { question: 'Do meta keywords still matter?', answer: 'No, Google has officially stated they do not use the meta keywords tag for ranking. Focus on title and description instead.' },
    ],
  },
  {
    slug: 'check-keyword-density',
    title: 'How to Check Keyword Density',
    description: 'Analyze keyword density and frequency in your content. Optimize your SEO without over-stuffing keywords.',
    toolSlug: 'keyword-density-checker',
    toolName: 'Keyword Density Checker',
    category: 'seo',
    steps: [
      { name: 'Open the Keyword Density Checker', text: 'Go to the Keyword Density Checker on UtilsNow. It analyzes your content in real time.' },
      { name: 'Paste your content', text: 'Paste the text of your blog post, article, or web page content into the input area.' },
      { name: 'View density analysis', text: 'The tool calculates the frequency and density percentage of every word and phrase in your content.' },
      { name: 'Check target keywords', text: 'Find your target keywords in the results and verify their density is between 1-3% for optimal SEO.' },
      { name: 'Adjust your content', text: 'If keyword density is too high (stuffing) or too low, adjust your content accordingly and re-analyze.' },
    ],
    faqs: [
      { question: 'What is the ideal keyword density?', answer: 'Most SEO experts recommend a keyword density of 1-3%. Exceeding 3% may be seen as keyword stuffing by search engines.' },
      { question: 'Does the tool check for keyword stuffing?', answer: 'Yes, the tool highlights words with unusually high density that might be flagged as keyword stuffing by search engines.' },
      { question: 'Should I check 2-word and 3-word phrases?', answer: 'Yes, the tool analyzes single words, 2-word phrases (bigrams), and 3-word phrases (trigrams) for comprehensive keyword analysis.' },
    ],
  },
  {
    slug: 'preview-serp-result',
    title: 'How to Preview Google Search Results (SERP)',
    description: 'Preview how your page will appear in Google search results. Optimize your title and description for clicks.',
    toolSlug: 'serp-preview',
    toolName: 'SERP Preview',
    category: 'seo',
    steps: [
      { name: 'Open the SERP Preview tool', text: 'Navigate to the SERP Preview tool on UtilsNow. It simulates Google search result appearance.' },
      { name: 'Enter your page URL', text: 'Type or paste the URL of your page. This is displayed in green text below the title in search results.' },
      { name: 'Write your title tag', text: 'Enter your page title. The tool shows if it fits within Google\'s character limit (50-60 characters) with a visual indicator.' },
      { name: 'Write your meta description', text: 'Enter your meta description (150-160 characters). The preview shows exactly how it will appear, including truncation.' },
      { name: 'Optimize and copy', text: 'Adjust your title and description until the preview looks compelling and fits within the limits. Copy the optimized meta tags.' },
    ],
    faqs: [
      { question: 'Does Google always show my exact meta description?', answer: 'No, Google may rewrite your meta description based on the search query. However, a well-written description is used more often.' },
      { question: 'What is the maximum title length for Google?', answer: 'Google typically displays 50-60 characters of the title tag. Titles longer than this may be truncated with an ellipsis (...).' },
      { question: 'Can I preview rich results?', answer: 'This tool previews standard search results. For rich results (FAQ, How-To, etc.), use structured data testing tools.' },
    ],
  },
  {
    slug: 'generate-robots-txt',
    title: 'How to Create a robots.txt File',
    description: 'Generate a robots.txt file for your website. Control which pages search engines can crawl and index.',
    toolSlug: 'robots-txt-generator',
    toolName: 'Robots.txt Generator',
    category: 'seo',
    steps: [
      { name: 'Open the Robots.txt Generator', text: 'Go to the Robots.txt Generator on UtilsNow. It helps create properly formatted robots.txt files.' },
      { name: 'Set user agents', text: 'Choose which search engine bots to configure rules for (Googlebot, Bingbot, or all bots with *).' },
      { name: 'Define allow and disallow rules', text: 'Specify which paths to allow (e.g., /) and disallow (e.g., /admin/, /private/) for each bot.' },
      { name: 'Add sitemap URL', text: 'Include your XML sitemap URL so search engines can discover all your pages efficiently.' },
      { name: 'Download the file', text: 'Copy or download the generated robots.txt file and place it in the root directory of your website.' },
    ],
    faqs: [
      { question: 'Where do I put the robots.txt file?', answer: 'The robots.txt file must be placed in the root directory of your domain. For example: https://example.com/robots.txt.' },
      { question: 'Can robots.txt block pages from Google?', answer: 'robots.txt prevents crawling but not indexing. Google may still index a page (without content) if other sites link to it. Use noindex meta tag to prevent indexing.' },
      { question: 'Should I block CSS and JavaScript files?', answer: 'No, Google recommends allowing access to CSS and JS files so it can render your pages properly for indexing.' },
    ],
  },
  {
    slug: 'generate-schema-markup',
    title: 'How to Generate FAQ Schema Markup',
    description: 'Create FAQ structured data (schema.org) for rich results in Google search. Boost click-through rates.',
    toolSlug: 'schema-faq',
    toolName: 'FAQ Schema Generator',
    category: 'seo',
    steps: [
      { name: 'Open the FAQ Schema Generator', text: 'Navigate to the FAQ Schema Generator on UtilsNow. It creates valid JSON-LD structured data.' },
      { name: 'Add your questions and answers', text: 'Enter each frequently asked question and its answer. Click "Add Question" to add more Q&A pairs.' },
      { name: 'Preview the schema', text: 'The tool generates the JSON-LD code in real time. Review the structured data to ensure accuracy.' },
      { name: 'Validate the output', text: 'The generated schema follows the schema.org FAQPage specification and is compatible with Google Rich Results.' },
      { name: 'Add to your page', text: 'Copy the JSON-LD script tag and paste it into the HTML of the page containing the FAQ content.' },
    ],
    faqs: [
      { question: 'What are FAQ rich results?', answer: 'FAQ rich results are expandable question-and-answer sections that appear directly in Google search results, increasing your listing visibility and click-through rate.' },
      { question: 'How many FAQs should I add?', answer: 'Google recommends including FAQs that are actually on your page. There is no strict limit, but 3-10 questions typically work best.' },
      { question: 'Does FAQ schema guarantee rich results?', answer: 'No, adding schema markup makes your page eligible for rich results, but Google decides which pages actually receive the enhanced display.' },
    ],
  },

  // ── Color Tools ─────────────────────────────────────────────────────────
  {
    slug: 'check-color-contrast',
    title: 'How to Check Color Contrast for Accessibility',
    description: 'Check WCAG color contrast ratios between text and background colors. Ensure your design meets accessibility standards.',
    toolSlug: 'contrast-checker',
    toolName: 'WCAG Contrast Checker',
    category: 'color',
    steps: [
      { name: 'Open the Contrast Checker', text: 'Navigate to the WCAG Contrast Checker on UtilsNow. It evaluates color combinations against accessibility standards.' },
      { name: 'Enter foreground color', text: 'Input your text color using HEX, RGB, or HSL format. You can also use the color picker.' },
      { name: 'Enter background color', text: 'Input your background color in the same format. The tool calculates the contrast ratio in real time.' },
      { name: 'Check WCAG compliance', text: 'The tool shows the contrast ratio and whether it passes WCAG AA (4.5:1 for normal text) and AAA (7:1 for normal text) standards.' },
      { name: 'Adjust colors if needed', text: 'If the contrast fails, adjust either color until you achieve the required ratio. The tool suggests similar colors that pass.' },
    ],
    faqs: [
      { question: 'What contrast ratio does WCAG AA require?', answer: 'WCAG AA requires a minimum contrast ratio of 4.5:1 for normal text and 3:1 for large text (18px+ or 14px bold).' },
      { question: 'What is the difference between WCAG AA and AAA?', answer: 'AA is the standard level (4.5:1 for text). AAA is enhanced (7:1 for text). Most websites aim for AA compliance as a minimum.' },
      { question: 'Why does color contrast matter?', answer: 'Good color contrast ensures that text is readable for people with visual impairments, including color blindness. It is also required by accessibility laws in many countries.' },
    ],
  },
  {
    slug: 'pick-color-from-image',
    title: 'How to Pick a Color from Any Image',
    description: 'Pick colors from images, get HEX/RGB values, and build palettes. Free online color picker tool.',
    toolSlug: 'color-picker',
    toolName: 'Color Picker',
    category: 'color',
    steps: [
      { name: 'Open the Color Picker', text: 'Go to the Color Picker tool on UtilsNow. It provides multiple ways to select and identify colors.' },
      { name: 'Choose your color', text: 'Use the color wheel, spectrum panel, or enter a specific value in HEX, RGB, HSL, or CMYK format.' },
      { name: 'Fine-tune the color', text: 'Use the hue slider and saturation/brightness panel to adjust the color precisely to your needs.' },
      { name: 'Get all color formats', text: 'The tool displays the selected color in HEX, RGB, HSL, and CMYK formats simultaneously.' },
      { name: 'Copy the color value', text: 'Click on any format to copy it to your clipboard. Use it in your CSS, design tool, or any application.' },
    ],
    faqs: [
      { question: 'What color formats are supported?', answer: 'The tool supports HEX (#RRGGBB), RGB (0-255), HSL (hue, saturation, lightness), and CMYK (for print) formats.' },
      { question: 'Can I pick colors from a live webpage?', answer: 'The tool works with its built-in color picker. For picking colors from live webpages, use your browser\'s built-in developer tools (F12) eyedropper.' },
      { question: 'How do I convert between color formats?', answer: 'The Color Picker shows all formats simultaneously. For dedicated conversion, try the Color Converter tool which handles batch conversions.' },
    ],
  },
  {
    slug: 'generate-color-palette',
    title: 'How to Generate a Color Palette',
    description: 'Generate beautiful color palettes from a base color. Create complementary, analogous, and triadic schemes.',
    toolSlug: 'color-palette-generator',
    toolName: 'Color Palette Generator',
    category: 'color',
    steps: [
      { name: 'Open the Color Palette Generator', text: 'Navigate to the Color Palette Generator on UtilsNow. Create harmonious color schemes instantly.' },
      { name: 'Choose a base color', text: 'Enter your primary brand color or choose one from the color picker to serve as the palette base.' },
      { name: 'Select harmony type', text: 'Choose from complementary, analogous, triadic, split-complementary, or monochromatic color harmonies.' },
      { name: 'Explore the palette', text: 'View the generated palette with each color shown in its HEX and RGB values. See how the colors work together.' },
      { name: 'Export the palette', text: 'Copy individual color codes or export the entire palette as CSS variables, Tailwind config, or a shareable link.' },
    ],
    faqs: [
      { question: 'What is a complementary color scheme?', answer: 'Complementary colors are opposite each other on the color wheel (e.g., blue and orange). They create high contrast and visual impact.' },
      { question: 'How many colors should a palette have?', answer: 'Most design systems use 3-5 primary colors plus neutral grays. Start with a primary, secondary, and accent color.' },
      { question: 'Can I generate palettes from an image?', answer: 'This tool generates palettes from a base color using color theory. For extracting colors from images, upload your image and use the color picker.' },
    ],
  },

  // ── CSS Tools ───────────────────────────────────────────────────────────
  {
    slug: 'generate-css-gradient',
    title: 'How to Generate CSS Gradients',
    description: 'Create beautiful CSS gradients with a visual editor. Generate linear, radial, and conic gradient code.',
    toolSlug: 'css-gradient-generator',
    toolName: 'CSS Gradient Generator',
    category: 'css',
    steps: [
      { name: 'Open the CSS Gradient Generator', text: 'Navigate to the CSS Gradient Generator on UtilsNow. Create gradients visually with instant CSS output.' },
      { name: 'Choose gradient type', text: 'Select linear, radial, or conic gradient. Linear gradients flow in one direction; radial gradients radiate from a center point.' },
      { name: 'Add and adjust colors', text: 'Click to add color stops. Drag them to set positions. Use the color picker to choose exact colors for each stop.' },
      { name: 'Set direction and angle', text: 'For linear gradients, set the angle (0-360 degrees). For radial gradients, choose the shape (circle or ellipse) and position.' },
      { name: 'Copy the CSS code', text: 'The tool generates the CSS code in real time. Copy the background property to use directly in your stylesheet.' },
    ],
    faqs: [
      { question: 'How many color stops can I add?', answer: 'You can add as many color stops as you want. Most gradients look best with 2-5 stops. More stops create more complex transitions.' },
      { question: 'What is the difference between linear and radial gradients?', answer: 'Linear gradients transition colors along a straight line. Radial gradients transition colors from a center point outward in a circular or elliptical shape.' },
      { question: 'Are CSS gradients supported in all browsers?', answer: 'Yes, CSS gradients are supported in all modern browsers including Chrome, Firefox, Safari, and Edge. No vendor prefixes are needed.' },
    ],
  },
  {
    slug: 'generate-box-shadow',
    title: 'How to Generate CSS Box Shadows',
    description: 'Create CSS box shadows visually. Adjust offset, blur, spread, and color with real-time preview.',
    toolSlug: 'css-box-shadow-generator',
    toolName: 'Box Shadow Generator',
    category: 'css',
    steps: [
      { name: 'Open the Box Shadow Generator', text: 'Go to the Box Shadow Generator on UtilsNow. Design box shadows with a visual interface.' },
      { name: 'Set horizontal and vertical offset', text: 'Use the sliders to adjust the shadow offset. Positive values move the shadow right/down; negative values move it left/up.' },
      { name: 'Adjust blur and spread', text: 'Set the blur radius (softness) and spread radius (size). Higher blur creates softer shadows; spread expands or contracts the shadow.' },
      { name: 'Choose shadow color and opacity', text: 'Pick a shadow color and adjust the opacity. For realistic shadows, use dark colors with 10-30% opacity.' },
      { name: 'Copy the CSS', text: 'Copy the generated box-shadow CSS property. You can add multiple shadows by stacking them for layered effects.' },
    ],
    faqs: [
      { question: 'What makes a realistic box shadow?', answer: 'Realistic shadows use subtle offsets (1-4px), moderate blur (8-24px), and low opacity (0.1-0.3). Avoid sharp, dark shadows for a natural look.' },
      { question: 'Can I have multiple box shadows?', answer: 'Yes, CSS supports multiple shadows separated by commas. Use the tool to create each shadow individually and combine them.' },
      { question: 'What is the inset shadow option?', answer: 'Inset shadows appear inside the element instead of outside, creating a recessed or pressed-in effect.' },
    ],
  },
  {
    slug: 'generate-flexbox-layout',
    title: 'How to Generate CSS Flexbox Layouts',
    description: 'Create CSS Flexbox layouts visually. Configure direction, alignment, wrapping, and gap with live preview.',
    toolSlug: 'css-flexbox-generator',
    toolName: 'Flexbox Generator',
    category: 'css',
    steps: [
      { name: 'Open the Flexbox Generator', text: 'Navigate to the Flexbox Generator on UtilsNow. Build flexbox layouts visually without memorizing properties.' },
      { name: 'Set flex direction', text: 'Choose row (horizontal) or column (vertical) layout direction. Select row-reverse or column-reverse for reversed order.' },
      { name: 'Configure alignment', text: 'Set justify-content (main axis alignment) and align-items (cross axis alignment). Options include center, space-between, flex-start, etc.' },
      { name: 'Add flex items', text: 'Add child elements and configure their flex-grow, flex-shrink, and flex-basis properties individually.' },
      { name: 'Copy the CSS code', text: 'Copy the generated CSS for both the container and child elements. The code is ready to paste into your project.' },
    ],
    faqs: [
      { question: 'When should I use Flexbox vs CSS Grid?', answer: 'Use Flexbox for one-dimensional layouts (row OR column). Use CSS Grid for two-dimensional layouts (rows AND columns). They work great together.' },
      { question: 'What does flex-wrap do?', answer: 'flex-wrap controls whether items wrap to the next line when they overflow the container. Set to "wrap" for responsive multi-line layouts.' },
      { question: 'What is the gap property?', answer: 'The gap property sets spacing between flex items without using margins. It works in all modern browsers and simplifies layout spacing.' },
    ],
  },

  // ── Financial Calculators ───────────────────────────────────────────────
  {
    slug: 'calculate-emi',
    title: 'How to Calculate EMI (Equated Monthly Installment)',
    description: 'Calculate EMI for home loans, car loans, and personal loans. See monthly payments, interest, and amortization.',
    toolSlug: 'emi-calculator',
    toolName: 'EMI Calculator',
    category: 'financial',
    steps: [
      { name: 'Open the EMI Calculator', text: 'Navigate to the EMI Calculator on UtilsNow. Calculate loan EMIs instantly with no signup.' },
      { name: 'Enter loan amount', text: 'Input the total loan principal amount you want to borrow or are considering.' },
      { name: 'Set interest rate', text: 'Enter the annual interest rate offered by your bank or lender. Use the current market rate for accurate results.' },
      { name: 'Choose loan tenure', text: 'Select the loan period in months or years. Longer tenure means lower EMI but more total interest paid.' },
      { name: 'View results', text: 'The calculator shows your monthly EMI, total interest payable, total payment amount, and an amortization schedule showing the principal vs interest breakdown.' },
    ],
    faqs: [
      { question: 'What is EMI?', answer: 'EMI (Equated Monthly Installment) is a fixed monthly payment made to repay a loan over a set period. It includes both principal repayment and interest.' },
      { question: 'How is EMI calculated?', answer: 'EMI = P * r * (1+r)^n / ((1+r)^n - 1), where P is principal, r is monthly interest rate, and n is number of months.' },
      { question: 'Should I choose a shorter or longer tenure?', answer: 'Shorter tenure means higher EMI but less total interest paid. Longer tenure means lower EMI but more interest over time. Choose based on your monthly budget.' },
    ],
  },
  {
    slug: 'calculate-compound-interest',
    title: 'How to Calculate Compound Interest',
    description: 'Calculate compound interest on investments and savings. See how your money grows over time with compounding.',
    toolSlug: 'compound-interest-calculator',
    toolName: 'Compound Interest Calculator',
    category: 'financial',
    steps: [
      { name: 'Open the Compound Interest Calculator', text: 'Go to the Compound Interest Calculator on UtilsNow. Visualize the power of compounding.' },
      { name: 'Enter principal amount', text: 'Input the initial investment or savings amount you are starting with.' },
      { name: 'Set interest rate', text: 'Enter the annual interest rate. This can be the expected return on investment or savings account rate.' },
      { name: 'Choose compounding frequency', text: 'Select how often interest compounds: annually, semi-annually, quarterly, monthly, or daily. More frequent compounding yields higher returns.' },
      { name: 'View the growth', text: 'See your total amount, interest earned, and a year-by-year breakdown showing how compound interest accelerates growth over time.' },
    ],
    faqs: [
      { question: 'What is compound interest?', answer: 'Compound interest is interest calculated on both the initial principal and the accumulated interest from previous periods. It makes your money grow faster than simple interest.' },
      { question: 'How does compounding frequency affect returns?', answer: 'More frequent compounding (daily vs annually) yields slightly higher returns because interest starts earning interest sooner. The difference is more noticeable with higher rates and longer periods.' },
      { question: 'What is the Rule of 72?', answer: 'The Rule of 72 estimates how long it takes to double your money: divide 72 by the interest rate. At 8% interest, money doubles in approximately 9 years (72/8 = 9).' },
    ],
  },
  {
    slug: 'calculate-mortgage',
    title: 'How to Calculate Mortgage Payments',
    description: 'Calculate monthly mortgage payments, total interest, and amortization schedule. Compare loan scenarios.',
    toolSlug: 'mortgage-calculator',
    toolName: 'Mortgage Calculator',
    category: 'financial',
    steps: [
      { name: 'Open the Mortgage Calculator', text: 'Navigate to the Mortgage Calculator on UtilsNow. Plan your home loan with accurate payment estimates.' },
      { name: 'Enter home price and down payment', text: 'Input the home purchase price and your planned down payment amount or percentage.' },
      { name: 'Set loan terms', text: 'Enter the interest rate and choose the loan term (15-year, 20-year, or 30-year fixed). Compare different terms to see how they affect payments.' },
      { name: 'Include additional costs', text: 'Add property tax rate, homeowner insurance, and PMI (if down payment is less than 20%) for a complete monthly payment estimate.' },
      { name: 'Review the breakdown', text: 'View your monthly payment broken down by principal, interest, taxes, and insurance. See the amortization schedule and total cost over the loan life.' },
    ],
    faqs: [
      { question: 'What is included in a mortgage payment?', answer: 'A typical mortgage payment includes principal repayment, interest, property taxes, and homeowner insurance (often abbreviated as PITI).' },
      { question: 'Is a 15-year or 30-year mortgage better?', answer: 'A 15-year mortgage has higher monthly payments but significantly less total interest. A 30-year mortgage has lower payments but you pay much more interest overall.' },
      { question: 'What is PMI?', answer: 'PMI (Private Mortgage Insurance) is required when your down payment is less than 20% of the home price. It typically costs 0.5-1% of the loan amount annually.' },
    ],
  },
  {
    slug: 'calculate-sip-returns',
    title: 'How to Calculate SIP Returns',
    description: 'Calculate SIP (Systematic Investment Plan) returns and future value. Plan your mutual fund investments.',
    toolSlug: 'sip-calculator',
    toolName: 'SIP Calculator',
    category: 'financial',
    steps: [
      { name: 'Open the SIP Calculator', text: 'Go to the SIP Calculator on UtilsNow. Estimate your mutual fund investment growth with SIP.' },
      { name: 'Enter monthly SIP amount', text: 'Input the amount you plan to invest every month through SIP. Start with an amount you can consistently invest.' },
      { name: 'Set expected return rate', text: 'Enter the expected annual return rate. Equity mutual funds have historically returned 12-15% in India over the long term.' },
      { name: 'Choose investment period', text: 'Select how many years you plan to continue the SIP. Longer investment periods benefit more from compounding.' },
      { name: 'View projected returns', text: 'See your total investment, estimated returns, and final corpus value. The chart shows how your wealth grows over time with the power of compounding.' },
    ],
    faqs: [
      { question: 'What is SIP?', answer: 'SIP (Systematic Investment Plan) is a method of investing a fixed amount regularly in mutual funds. It averages out market volatility through rupee cost averaging.' },
      { question: 'What return rate should I assume for SIP?', answer: 'For equity mutual funds, 12-15% annual returns is a reasonable long-term assumption. For debt funds, assume 6-8%. Always consider these as estimates, not guarantees.' },
      { question: 'Is SIP better than lump sum investment?', answer: 'SIP reduces the risk of investing at market peaks through rupee cost averaging. Lump sum may give higher returns in consistently rising markets, but SIP is safer for most investors.' },
    ],
  },
  {
    slug: 'calculate-percentage',
    title: 'How to Calculate Percentages',
    description: 'Calculate any percentage of any number. Find percentage increase, decrease, and difference with formulas.',
    toolSlug: 'percentage-calculator',
    toolName: 'Percentage Calculator',
    category: 'financial',
    steps: [
      { name: 'Open the Percentage Calculator', text: 'Navigate to the Percentage Calculator on UtilsNow. Solve any percentage calculation instantly.' },
      { name: 'Choose calculation type', text: 'Select what you want to calculate: "What is X% of Y?", "X is what % of Y?", or "Percentage increase/decrease from X to Y".' },
      { name: 'Enter your values', text: 'Input the numbers for your calculation. For example, enter 25 and 200 to find what 25% of 200 is.' },
      { name: 'View the result', text: 'The calculator instantly shows the answer with the formula and step-by-step calculation breakdown.' },
      { name: 'Try related calculations', text: 'Use the related calculations section to explore similar percentage problems with different values.' },
    ],
    faqs: [
      { question: 'How do I calculate a percentage of a number?', answer: 'Multiply the number by the percentage and divide by 100. For example: 25% of 200 = 200 x 25 / 100 = 50.' },
      { question: 'How do I calculate percentage increase?', answer: 'Percentage increase = ((New Value - Old Value) / Old Value) x 100. For example, going from 80 to 100 is a 25% increase.' },
      { question: 'How do I find what percentage one number is of another?', answer: 'Divide the part by the whole and multiply by 100. For example, 50 is 25% of 200 because (50/200) x 100 = 25%.' },
    ],
  },

  // ── Converters ──────────────────────────────────────────────────────────
  {
    slug: 'convert-unix-timestamp',
    title: 'How to Convert Unix Timestamps',
    description: 'Convert Unix timestamps to human-readable dates and vice versa. Support for seconds and milliseconds.',
    toolSlug: 'unix-timestamp-converter',
    toolName: 'Unix Timestamp Converter',
    category: 'converters',
    steps: [
      { name: 'Open the Unix Timestamp Converter', text: 'Navigate to the Unix Timestamp Converter on UtilsNow. Convert timestamps to dates and dates to timestamps.' },
      { name: 'Enter a timestamp or date', text: 'Input a Unix timestamp (e.g., 1691712000) to convert to a date, or enter a date to get its Unix timestamp.' },
      { name: 'Choose precision', text: 'Select whether your timestamp is in seconds (10 digits) or milliseconds (13 digits, common in JavaScript).' },
      { name: 'View the conversion', text: 'See the converted date in multiple formats: ISO 8601, local time, UTC, and relative time (e.g., "2 hours ago").' },
      { name: 'Copy the result', text: 'Copy the converted value in your preferred format for use in your code, database, or documentation.' },
    ],
    faqs: [
      { question: 'What is a Unix timestamp?', answer: 'A Unix timestamp is the number of seconds (or milliseconds) elapsed since January 1, 1970 00:00:00 UTC, known as the Unix Epoch.' },
      { question: 'Why do some timestamps have 10 digits and others 13?', answer: 'A 10-digit timestamp is in seconds (used by most backend systems). A 13-digit timestamp is in milliseconds (used by JavaScript Date.now() and some APIs).' },
      { question: 'Does the converter handle negative timestamps?', answer: 'Yes, negative timestamps represent dates before January 1, 1970. For example, -86400 represents December 31, 1969.' },
    ],
  },
  {
    slug: 'convert-colors',
    title: 'How to Convert Between Color Formats',
    description: 'Convert colors between HEX, RGB, HSL, and CMYK formats. Free online color converter with preview.',
    toolSlug: 'color-converter',
    toolName: 'Color Converter',
    category: 'converters',
    steps: [
      { name: 'Open the Color Converter', text: 'Go to the Color Converter on UtilsNow. Convert between all major color formats instantly.' },
      { name: 'Enter your color value', text: 'Input a color in any supported format: HEX (#FF5733), RGB (255, 87, 51), HSL (11, 100%, 60%), or CMYK.' },
      { name: 'View all conversions', text: 'The tool instantly shows the same color in all formats. HEX for CSS, RGB for programming, HSL for design, and CMYK for print.' },
      { name: 'Preview the color', text: 'See a large color swatch showing exactly how the color looks, ensuring you have the right shade.' },
      { name: 'Copy any format', text: 'Click to copy any color format to your clipboard. Each format is ready to paste into CSS, code, or design tools.' },
    ],
    faqs: [
      { question: 'Which color format should I use for web?', answer: 'HEX (#RRGGBB) is the most common for CSS. RGB/RGBA is used when you need transparency. HSL is useful for creating color variations.' },
      { question: 'What is CMYK used for?', answer: 'CMYK (Cyan, Magenta, Yellow, Key/Black) is used for print design. Colors can look different in CMYK vs RGB, so always check print proofs.' },
      { question: 'Can I convert named colors?', answer: 'Yes, you can enter CSS named colors (like "coral", "steelblue") and the tool will show their values in all formats.' },
    ],
  },
  {
    slug: 'convert-css-units',
    title: 'How to Convert CSS Units (px, rem, em, vw)',
    description: 'Convert between CSS units like px, rem, em, vw, vh, and percentages. Essential for responsive web design.',
    toolSlug: 'css-unit-converter',
    toolName: 'CSS Unit Converter',
    category: 'converters',
    steps: [
      { name: 'Open the CSS Unit Converter', text: 'Navigate to the CSS Unit Converter on UtilsNow. Convert between all CSS length units.' },
      { name: 'Enter a value and source unit', text: 'Type a number and select the source unit (px, rem, em, pt, vw, vh, %, etc.).' },
      { name: 'Set the base font size', text: 'For rem and em conversions, set the base font size (default is 16px). This affects the conversion ratio.' },
      { name: 'View all conversions', text: 'The tool shows the equivalent value in all CSS units simultaneously, making it easy to compare.' },
      { name: 'Copy the converted value', text: 'Copy the converted CSS value including the unit suffix, ready to paste into your stylesheet.' },
    ],
    faqs: [
      { question: 'What is the difference between rem and em?', answer: 'rem is relative to the root (html) font size. em is relative to the parent element font size. rem is more predictable and generally preferred.' },
      { question: 'Should I use px or rem?', answer: 'Use rem for font sizes and spacing (respects user font size preferences). Use px for borders and very small fixed-size elements.' },
      { question: 'How do I convert px to rem?', answer: 'Divide the pixel value by the base font size (default 16px). For example: 24px / 16 = 1.5rem.' },
    ],
  },

  // ── Encoders & Decoders ─────────────────────────────────────────────────
  {
    slug: 'encode-base64',
    title: 'How to Encode and Decode Base64',
    description: 'Encode text to Base64 or decode Base64 to text online. Essential for APIs, data URIs, and email encoding.',
    toolSlug: 'base64-encoder',
    toolName: 'Base64 Encoder/Decoder',
    category: 'encoders',
    steps: [
      { name: 'Open the Base64 Encoder', text: 'Navigate to the Base64 Encoder/Decoder on UtilsNow. Encode or decode Base64 strings instantly.' },
      { name: 'Choose encode or decode mode', text: 'Select Encode to convert text to Base64, or Decode to convert Base64 back to readable text.' },
      { name: 'Paste your input', text: 'For encoding: paste the text or data you want to encode. For decoding: paste the Base64 string.' },
      { name: 'View the result', text: 'The tool instantly processes your input and shows the encoded or decoded output in the result area.' },
      { name: 'Copy the output', text: 'Copy the Base64 encoded string for use in APIs, data URIs, email headers, or other applications.' },
    ],
    faqs: [
      { question: 'What is Base64 encoding?', answer: 'Base64 is a binary-to-text encoding scheme that represents binary data using 64 ASCII characters (A-Z, a-z, 0-9, +, /). It is commonly used to embed data in text-based formats.' },
      { question: 'Why is Base64 used?', answer: 'Base64 is used to safely transmit binary data through text-based protocols like email (MIME), JSON APIs, data URIs in HTML/CSS, and Basic HTTP authentication.' },
      { question: 'Does Base64 increase file size?', answer: 'Yes, Base64 encoding increases the data size by approximately 33%. A 1KB file becomes about 1.33KB when Base64 encoded.' },
    ],
  },
  {
    slug: 'encode-url',
    title: 'How to URL Encode and Decode Text',
    description: 'Encode special characters for URLs or decode percent-encoded URLs. Handle query parameters safely.',
    toolSlug: 'url-encoder',
    toolName: 'URL Encoder/Decoder',
    category: 'encoders',
    steps: [
      { name: 'Open the URL Encoder', text: 'Go to the URL Encoder/Decoder on UtilsNow. Encode or decode URL strings safely.' },
      { name: 'Choose encode or decode', text: 'Select Encode to convert special characters to percent-encoding, or Decode to convert them back.' },
      { name: 'Paste your text or URL', text: 'For encoding: paste text with special characters. For decoding: paste a URL with %20, %3D, etc.' },
      { name: 'View the result', text: 'Spaces become %20, ampersands become %26, equals become %3D, and all other special characters are properly encoded.' },
      { name: 'Copy the encoded URL', text: 'Copy the encoded string for safe use in URLs, API requests, query parameters, or form submissions.' },
    ],
    faqs: [
      { question: 'Why do URLs need encoding?', answer: 'URLs can only contain certain ASCII characters. Special characters like spaces, &, =, and non-ASCII characters must be percent-encoded to be valid in URLs.' },
      { question: 'What is the difference between encodeURI and encodeURIComponent?', answer: 'encodeURI encodes a full URL but preserves special URL characters (:, /, ?, #, &). encodeURIComponent encodes everything, suitable for query parameter values.' },
      { question: 'Is URL encoding the same as percent encoding?', answer: 'Yes, URL encoding and percent encoding are the same thing. Characters are replaced with % followed by their hexadecimal ASCII value.' },
    ],
  },
  {
    slug: 'generate-hash',
    title: 'How to Generate Hash Values (MD5, SHA-256)',
    description: 'Generate MD5, SHA-1, SHA-256, and SHA-512 hash values from text. Useful for checksums and data integrity.',
    toolSlug: 'hash-generator',
    toolName: 'Hash Generator',
    category: 'encoders',
    steps: [
      { name: 'Open the Hash Generator', text: 'Navigate to the Hash Generator on UtilsNow. Generate cryptographic hashes entirely in your browser.' },
      { name: 'Enter your text', text: 'Type or paste the text you want to hash. Even a tiny change in input produces a completely different hash.' },
      { name: 'Choose hash algorithm', text: 'Select the algorithm: MD5 (fast, legacy), SHA-1 (legacy), SHA-256 (recommended), or SHA-512 (strongest).' },
      { name: 'View the hash', text: 'The tool instantly generates the hash value as a hexadecimal string. The output length depends on the algorithm chosen.' },
      { name: 'Copy the hash', text: 'Copy the hash value for use in checksum verification, data integrity checks, or API authentication.' },
    ],
    faqs: [
      { question: 'Which hash algorithm should I use?', answer: 'Use SHA-256 for general purposes. MD5 and SHA-1 are considered cryptographically broken and should not be used for security. They are still fine for checksums.' },
      { question: 'Can I reverse a hash to get the original text?', answer: 'No, hash functions are one-way. You cannot reverse a hash to recover the original input. This is by design for security purposes.' },
      { question: 'Why do small changes produce completely different hashes?', answer: 'This is called the "avalanche effect." Even changing one character produces a completely different hash, making hashes useful for detecting data tampering.' },
    ],
  },

  // ── Generators ──────────────────────────────────────────────────────────
  {
    slug: 'generate-password',
    title: 'How to Generate a Strong Password',
    description: 'Generate secure, random passwords with customizable length, characters, and complexity requirements.',
    toolSlug: 'password-generator',
    toolName: 'Password Generator',
    category: 'generators',
    steps: [
      { name: 'Open the Password Generator', text: 'Navigate to the Password Generator on UtilsNow. Create strong passwords with cryptographic randomness.' },
      { name: 'Set password length', text: 'Choose your desired password length. 12-16 characters is recommended minimum; 20+ characters is ideal for high-security accounts.' },
      { name: 'Select character types', text: 'Toggle uppercase letters, lowercase letters, numbers, and special characters. Include all types for maximum strength.' },
      { name: 'Exclude ambiguous characters', text: 'Optionally exclude visually similar characters (0/O, 1/l/I) for passwords you might need to type manually.' },
      { name: 'Copy and save securely', text: 'Copy the generated password and save it in a password manager. Never reuse passwords across different accounts.' },
    ],
    faqs: [
      { question: 'How long should a password be?', answer: 'At least 12 characters for standard accounts, 16+ for sensitive accounts like banking and email. Each additional character exponentially increases security.' },
      { question: 'Are these passwords truly random?', answer: 'Yes, the tool uses the Web Crypto API (crypto.getRandomValues) which provides cryptographically secure random numbers, the same standard used by password managers.' },
      { question: 'Should I include special characters?', answer: 'Yes, including special characters (!@#$%^&*) significantly increases password entropy. A 12-character password with all character types has over 475 trillion combinations.' },
    ],
  },
  {
    slug: 'generate-uuid',
    title: 'How to Generate UUID/GUID',
    description: 'Generate UUID v4 (random) and other UUID versions online. Create unique identifiers for databases and APIs.',
    toolSlug: 'uuid-generator',
    toolName: 'UUID Generator',
    category: 'generators',
    steps: [
      { name: 'Open the UUID Generator', text: 'Go to the UUID Generator on UtilsNow. Generate universally unique identifiers instantly.' },
      { name: 'Choose UUID version', text: 'Select UUID v4 (random, most common), UUID v1 (timestamp-based), or other versions based on your needs.' },
      { name: 'Generate one or many', text: 'Click Generate to create a single UUID, or specify a count to generate multiple UUIDs at once.' },
      { name: 'Choose format', text: 'View the UUID in standard format (with hyphens), compact format (no hyphens), or uppercase.' },
      { name: 'Copy and use', text: 'Copy the UUID(s) for use as database primary keys, API tokens, session IDs, or unique filenames.' },
    ],
    faqs: [
      { question: 'What is a UUID?', answer: 'UUID (Universally Unique Identifier) is a 128-bit identifier that is practically unique worldwide. The chance of collision with UUID v4 is approximately 1 in 5.3 x 10^36.' },
      { question: 'What is the difference between UUID and GUID?', answer: 'UUID and GUID (Globally Unique Identifier) are the same thing. UUID is the standard term (RFC 4122), while GUID is Microsoft\'s terminology.' },
      { question: 'Which UUID version should I use?', answer: 'UUID v4 (random) is the most commonly used. It is simple, has no privacy concerns (unlike v1 which includes MAC address), and has an extremely low collision probability.' },
    ],
  },
  {
    slug: 'generate-lorem-ipsum',
    title: 'How to Generate Lorem Ipsum Placeholder Text',
    description: 'Generate lorem ipsum dummy text for design mockups and prototypes. Customizable paragraphs, sentences, or words.',
    toolSlug: 'lorem-ipsum-generator',
    toolName: 'Lorem Ipsum Generator',
    category: 'generators',
    steps: [
      { name: 'Open the Lorem Ipsum Generator', text: 'Navigate to the Lorem Ipsum Generator on UtilsNow. Create placeholder text for your designs.' },
      { name: 'Choose text unit', text: 'Select whether you want to generate paragraphs, sentences, or words of lorem ipsum text.' },
      { name: 'Set the amount', text: 'Enter how many paragraphs, sentences, or words you need. The tool generates realistic-looking Latin placeholder text.' },
      { name: 'Toggle options', text: 'Choose whether to start with the classic "Lorem ipsum dolor sit amet..." or begin with random text.' },
      { name: 'Copy the text', text: 'Copy the generated placeholder text and paste it into your design mockup, website template, or prototype.' },
    ],
    faqs: [
      { question: 'What is Lorem Ipsum?', answer: 'Lorem Ipsum is scrambled Latin text based on Cicero\'s "De Finibus Bonorum et Malorum" (45 BC). It has been used as placeholder text in the printing industry since the 1500s.' },
      { question: 'Why use Lorem Ipsum instead of real text?', answer: 'Lorem Ipsum helps designers and developers focus on layout and visual design without being distracted by readable content. It has a natural letter distribution similar to English.' },
      { question: 'Can I generate text in other languages?', answer: 'This tool generates classic Latin-based Lorem Ipsum. For placeholder text in specific languages, you would need a language-specific generator.' },
    ],
  },
  {
    slug: 'generate-barcode',
    title: 'How to Generate Barcodes Online',
    description: 'Generate barcodes in Code 128, EAN-13, UPC-A, and other formats. Free barcode generator with download.',
    toolSlug: 'barcode-generator',
    toolName: 'Barcode Generator',
    category: 'generators',
    steps: [
      { name: 'Open the Barcode Generator', text: 'Go to the Barcode Generator on UtilsNow. Create barcodes in multiple standard formats.' },
      { name: 'Enter your data', text: 'Type or paste the text, number, or code you want to encode as a barcode.' },
      { name: 'Choose barcode format', text: 'Select the barcode type: Code 128 (general), EAN-13 (products), UPC-A (US retail), Code 39, or others based on your use case.' },
      { name: 'Customize appearance', text: 'Set the barcode width, height, and whether to display the text label below the bars.' },
      { name: 'Download the barcode', text: 'Download your barcode as a PNG or SVG image. SVG is recommended for print to ensure sharp output at any size.' },
    ],
    faqs: [
      { question: 'Which barcode format should I use?', answer: 'Code 128 is the most versatile for general use. EAN-13 is standard for international retail products. UPC-A is used for US and Canadian retail products.' },
      { question: 'What data can I encode in a barcode?', answer: 'Code 128 supports all ASCII characters. Numeric-only formats like EAN-13 and UPC-A are limited to specific digit counts (13 and 12 respectively).' },
      { question: 'What is the difference between barcodes and QR codes?', answer: 'Barcodes are one-dimensional (lines) and store limited data. QR codes are two-dimensional (squares) and can store much more data including URLs and text.' },
    ],
  },
  {
    slug: 'generate-gitignore',
    title: 'How to Generate a .gitignore File',
    description: 'Generate .gitignore files for any programming language or framework. Node.js, Python, Java, React, and more.',
    toolSlug: 'gitignore-generator',
    toolName: '.gitignore Generator',
    category: 'generators',
    steps: [
      { name: 'Open the .gitignore Generator', text: 'Navigate to the .gitignore Generator on UtilsNow. Create gitignore files for any tech stack.' },
      { name: 'Select your technologies', text: 'Choose the programming languages, frameworks, and tools you use (e.g., Node.js, Python, React, macOS, VS Code).' },
      { name: 'Review the generated rules', text: 'The tool combines ignore rules for all selected technologies, removing duplicates and organizing by category.' },
      { name: 'Customize if needed', text: 'Add or remove specific rules. Common additions include .env files, build directories, and IDE configuration folders.' },
      { name: 'Download or copy', text: 'Copy the .gitignore content or download it as a file. Place it in your project root directory.' },
    ],
    faqs: [
      { question: 'What is a .gitignore file?', answer: 'A .gitignore file tells Git which files and directories to ignore (not track). It prevents committing temporary files, dependencies, secrets, and build artifacts.' },
      { question: 'Where should I put the .gitignore file?', answer: 'Place it in the root directory of your Git repository. You can also have .gitignore files in subdirectories for folder-specific rules.' },
      { question: 'Does .gitignore remove already tracked files?', answer: 'No, .gitignore only affects untracked files. To stop tracking a file already committed, run: git rm --cached <file>' },
    ],
  },

  // ── Additional guides for more tool coverage ────────────────────────────
  {
    slug: 'create-markdown-table',
    title: 'How to Create Markdown Tables',
    description: 'Generate Markdown tables visually. Add rows, columns, and alignment without memorizing Markdown syntax.',
    toolSlug: 'markdown-table-generator',
    toolName: 'Markdown Table Generator',
    category: 'developer',
    steps: [
      { name: 'Open the Markdown Table Generator', text: 'Navigate to the Markdown Table Generator on UtilsNow. Create tables visually without knowing Markdown syntax.' },
      { name: 'Set table dimensions', text: 'Specify the number of rows and columns for your table. You can add or remove rows and columns later.' },
      { name: 'Enter cell content', text: 'Click on each cell and type your content. The tool generates the Markdown syntax automatically.' },
      { name: 'Set column alignment', text: 'Choose left, center, or right alignment for each column using the alignment buttons.' },
      { name: 'Copy the Markdown', text: 'Copy the generated Markdown table code and paste it into your README, documentation, or any Markdown file.' },
    ],
    faqs: [
      { question: 'Does Markdown support merged cells?', answer: 'Standard Markdown does not support merged cells (colspan/rowspan). For complex tables, consider using HTML tables within your Markdown.' },
      { question: 'Can I import data from a spreadsheet?', answer: 'You can paste tab-separated data from a spreadsheet. The tool will automatically format it into a Markdown table.' },
      { question: 'What is the Markdown table syntax?', answer: 'Markdown tables use pipes (|) to separate columns and hyphens (---) for the header separator. Colons (:) control alignment.' },
    ],
  },
  {
    slug: 'convert-markdown-to-html',
    title: 'How to Convert Markdown to HTML',
    description: 'Convert Markdown text to HTML code online. Supports GitHub Flavored Markdown with tables, task lists, and code blocks.',
    toolSlug: 'markdown-to-html',
    toolName: 'Markdown to HTML',
    category: 'developer',
    steps: [
      { name: 'Open the Markdown to HTML tool', text: 'Go to the Markdown to HTML converter on UtilsNow. It supports GitHub Flavored Markdown (GFM).' },
      { name: 'Enter your Markdown', text: 'Type or paste your Markdown content in the input area. The tool processes headings, lists, links, images, code blocks, and more.' },
      { name: 'Preview the output', text: 'See a live preview of the rendered HTML alongside the raw HTML code output.' },
      { name: 'Configure options', text: 'Choose whether to include a complete HTML document wrapper or just the content, and select sanitization options.' },
      { name: 'Copy the HTML', text: 'Copy the generated HTML code for use in your website, email template, or CMS.' },
    ],
    faqs: [
      { question: 'What Markdown features are supported?', answer: 'The tool supports all standard Markdown plus GFM extensions: tables, task lists, strikethrough, fenced code blocks with syntax highlighting, and autolinks.' },
      { question: 'Is the HTML output sanitized?', answer: 'Yes, the output is sanitized to prevent XSS attacks. Dangerous HTML tags and attributes are removed while keeping safe formatting.' },
      { question: 'Can I convert HTML back to Markdown?', answer: 'Yes, UtilsNow also offers an HTML to Markdown converter tool for the reverse conversion.' },
    ],
  },
  {
    slug: 'calculate-bmi',
    title: 'How to Calculate BMI (Body Mass Index)',
    description: 'Calculate your BMI using height and weight. Get your BMI category and health recommendations.',
    toolSlug: 'bmi-calculator',
    toolName: 'BMI Calculator',
    category: 'financial',
    steps: [
      { name: 'Open the BMI Calculator', text: 'Navigate to the BMI Calculator on UtilsNow. Calculate your Body Mass Index instantly.' },
      { name: 'Select your unit system', text: 'Choose between metric (kg/cm) or imperial (lbs/inches) measurement units.' },
      { name: 'Enter your weight', text: 'Input your weight in kilograms or pounds. Be as accurate as possible for a reliable result.' },
      { name: 'Enter your height', text: 'Input your height in centimeters, meters, or feet and inches depending on your selected unit system.' },
      { name: 'View your BMI result', text: 'The calculator shows your BMI value and category: Underweight (< 18.5), Normal (18.5-24.9), Overweight (25-29.9), or Obese (30+).' },
    ],
    faqs: [
      { question: 'What is a healthy BMI range?', answer: 'A BMI of 18.5 to 24.9 is considered healthy for most adults. However, BMI does not account for muscle mass, bone density, or body composition.' },
      { question: 'How is BMI calculated?', answer: 'BMI = weight (kg) / height (m)^2. In imperial units: BMI = (weight in lbs * 703) / (height in inches)^2.' },
      { question: 'Is BMI accurate for athletes?', answer: 'BMI may overestimate body fat in muscular athletes and underestimate it in elderly people. It is a screening tool, not a diagnostic measure.' },
    ],
  },
  {
    slug: 'calculate-age',
    title: 'How to Calculate Your Exact Age',
    description: 'Calculate your exact age in years, months, days, hours, and minutes from your date of birth.',
    toolSlug: 'age-calculator',
    toolName: 'Age Calculator',
    category: 'converters',
    steps: [
      { name: 'Open the Age Calculator', text: 'Navigate to the Age Calculator on UtilsNow. Find your exact age down to the minute.' },
      { name: 'Enter your date of birth', text: 'Select or type your date of birth using the date picker. You can also enter the year, month, and day manually.' },
      { name: 'Set the target date', text: 'By default, the tool calculates your age as of today. Optionally, set a different target date to calculate age at a specific point.' },
      { name: 'View your exact age', text: 'The calculator shows your age in years, months, and days. It also shows total days, weeks, hours, and minutes lived.' },
      { name: 'Check upcoming milestones', text: 'See your next birthday, how many days until it, and upcoming age milestones.' },
    ],
    faqs: [
      { question: 'Does it account for leap years?', answer: 'Yes, the calculator correctly handles leap years, including the leap year rules for century years (divisible by 400).' },
      { question: 'Can I calculate age between two dates?', answer: 'Yes, enter any start date and end date to calculate the exact time difference between them.' },
      { question: 'How is age calculated when born on February 29?', answer: 'For people born on February 29, the tool considers March 1 as the birthday in non-leap years.' },
    ],
  },
  {
    slug: 'build-cron-expression',
    title: 'How to Build Cron Expressions',
    description: 'Build and understand cron expressions visually. Schedule tasks with minute, hour, day, month, and weekday fields.',
    toolSlug: 'cron-expression-builder',
    toolName: 'Cron Expression Builder',
    category: 'developer',
    steps: [
      { name: 'Open the Cron Expression Builder', text: 'Navigate to the Cron Expression Builder on UtilsNow. Create cron schedules visually.' },
      { name: 'Set the schedule using dropdowns', text: 'Use the visual interface to select when your task should run: minute, hour, day of month, month, and day of week.' },
      { name: 'Choose common presets', text: 'Use preset schedules like "Every minute", "Every hour", "Daily at midnight", "Every Monday", or "Monthly" as a starting point.' },
      { name: 'View the cron expression', text: 'The tool generates the cron expression (e.g., "0 9 * * 1-5" for weekdays at 9 AM) with a human-readable description.' },
      { name: 'Copy and use', text: 'Copy the cron expression for use in crontab, GitHub Actions, CI/CD pipelines, or any scheduling system.' },
    ],
    faqs: [
      { question: 'What is a cron expression?', answer: 'A cron expression is a string of 5 fields (minute, hour, day, month, weekday) that defines a recurring schedule. It is used by Unix/Linux cron and many scheduling systems.' },
      { question: 'What does * mean in cron?', answer: 'The asterisk (*) means "every". For example, * in the hour field means "every hour". */5 means "every 5th" (e.g., every 5 minutes).' },
      { question: 'Can I schedule a task for specific days?', answer: 'Yes, use the day-of-week field: 0=Sunday, 1=Monday, ..., 6=Saturday. Example: "0 9 * * 1-5" runs at 9 AM on weekdays only.' },
    ],
  },
  {
    slug: 'generate-open-graph-tags',
    title: 'How to Create Open Graph Tags for Social Media',
    description: 'Generate Open Graph meta tags to control how your pages appear when shared on Facebook, LinkedIn, and Twitter.',
    toolSlug: 'open-graph-preview',
    toolName: 'Open Graph Preview',
    category: 'seo',
    steps: [
      { name: 'Open the Open Graph Preview tool', text: 'Navigate to the Open Graph Preview on UtilsNow. Create and preview OG tags for social sharing.' },
      { name: 'Enter your page details', text: 'Fill in the title (og:title), description (og:description), image URL (og:image), and page URL (og:url).' },
      { name: 'Preview social cards', text: 'See exactly how your page will appear when shared on Facebook, LinkedIn, and Twitter with the preview cards.' },
      { name: 'Optimize for engagement', text: 'Adjust your title and description for maximum click-through. Keep titles under 60 characters and descriptions under 155 characters.' },
      { name: 'Copy the meta tags', text: 'Copy the generated Open Graph HTML meta tags and add them to the <head> section of your web page.' },
    ],
    faqs: [
      { question: 'What is Open Graph?', answer: 'Open Graph is a protocol created by Facebook that lets you control how URLs are displayed when shared on social media. It defines the title, description, and image shown in the preview card.' },
      { question: 'What size should the OG image be?', answer: 'The recommended OG image size is 1200x630 pixels. This works well across Facebook, LinkedIn, and Twitter. Use a minimum of 600x315 pixels.' },
      { question: 'Do Twitter Cards use Open Graph?', answer: 'Twitter has its own meta tags (twitter:card, twitter:title, etc.) but falls back to Open Graph tags when Twitter-specific tags are not present.' },
    ],
  },
  {
    slug: 'convert-image-to-base64',
    title: 'How to Convert an Image to Base64',
    description: 'Convert images to Base64 encoded strings for embedding in HTML, CSS, and JSON. No server upload needed.',
    toolSlug: 'image-to-base64',
    toolName: 'Image to Base64',
    category: 'image',
    steps: [
      { name: 'Open the Image to Base64 tool', text: 'Navigate to the Image to Base64 converter on UtilsNow. Process images locally in your browser.' },
      { name: 'Upload your image', text: 'Drag and drop an image or click to browse. Supports PNG, JPG, WebP, GIF, SVG, and other formats.' },
      { name: 'View the Base64 output', text: 'The tool converts the image to a Base64 encoded string with the appropriate data URI prefix (data:image/png;base64,...).' },
      { name: 'Choose output format', text: 'Copy just the Base64 string, the full data URI, an HTML <img> tag, or a CSS background-image property.' },
      { name: 'Use in your project', text: 'Paste the Base64 string into your HTML, CSS, or JSON. This eliminates the need for a separate image file and HTTP request.' },
    ],
    faqs: [
      { question: 'Why convert images to Base64?', answer: 'Base64 images can be embedded directly in HTML and CSS, eliminating extra HTTP requests. This is useful for small icons, email templates, and single-file HTML documents.' },
      { question: 'Is Base64 efficient for large images?', answer: 'No, Base64 increases file size by ~33%. Use it for small images (under 10KB) like icons and logos. For larger images, use regular file references.' },
      { question: 'Can I convert Base64 back to an image?', answer: 'Yes, you can decode a Base64 string back to an image file. The tool also supports decoding when you paste a Base64 string.' },
    ],
  },
  {
    slug: 'generate-utm-links',
    title: 'How to Build UTM Tracking Links',
    description: 'Create UTM-tagged URLs for campaign tracking in Google Analytics. Track traffic sources accurately.',
    toolSlug: 'utm-link-builder',
    toolName: 'UTM Link Builder',
    category: 'seo',
    steps: [
      { name: 'Open the UTM Link Builder', text: 'Navigate to the UTM Link Builder on UtilsNow. Create trackable campaign URLs for Google Analytics.' },
      { name: 'Enter your destination URL', text: 'Paste the URL of the page you want to track (e.g., https://example.com/landing-page).' },
      { name: 'Fill in required UTM parameters', text: 'Enter utm_source (e.g., facebook), utm_medium (e.g., social), and utm_campaign (e.g., summer-sale-2024).' },
      { name: 'Add optional parameters', text: 'Optionally add utm_term (for paid keywords) and utm_content (for A/B testing different ads or links).' },
      { name: 'Copy the tagged URL', text: 'Copy the complete UTM-tagged URL and use it in your marketing campaigns. Traffic from this link will be tracked in Google Analytics.' },
    ],
    faqs: [
      { question: 'What are UTM parameters?', answer: 'UTM (Urchin Tracking Module) parameters are tags added to URLs that tell Google Analytics where traffic came from. They track source, medium, campaign, term, and content.' },
      { question: 'Which UTM parameters are required?', answer: 'utm_source, utm_medium, and utm_campaign are the recommended minimum. utm_term and utm_content are optional but useful for detailed tracking.' },
      { question: 'Do UTM parameters affect SEO?', answer: 'UTM parameters do not directly affect SEO rankings. However, use canonical URLs to prevent duplicate content when the same page has multiple UTM-tagged versions.' },
    ],
  },
]

export function getHowToGuideBySlug(slug: string): HowToGuide | undefined {
  return HOW_TO_GUIDES.find((g) => g.slug === slug)
}

export function getHowToGuidesByCategory(categoryId: string): HowToGuide[] {
  return HOW_TO_GUIDES.filter((g) => g.category === categoryId)
}
