'use client'

import { useState } from 'react'
import { ToolPage, ToolTextarea, CopyButton, DownloadButton, ClearButton } from '@/components/tool-page'

function toClassName(str: string): string {
  return str
    .replace(/[^a-zA-Z0-9]/g, ' ')
    .split(/\s+/)
    .filter(Boolean)
    .map((w) => w.charAt(0).toUpperCase() + w.slice(1))
    .join('')
}

function toSnakeCase(str: string): string {
  return str
    .replace(/([A-Z])/g, '_$1')
    .replace(/[^a-zA-Z0-9]/g, '_')
    .replace(/_+/g, '_')
    .replace(/^_/, '')
    .toLowerCase()
}

function pyType(value: unknown): string {
  if (value === null || value === undefined) return 'Optional[str]'
  if (typeof value === 'boolean') return 'bool'
  if (typeof value === 'number') return Number.isInteger(value) ? 'int' : 'float'
  if (typeof value === 'string') return 'str'
  if (Array.isArray(value)) {
    if (value.length === 0) return 'List'
    const inner = pyType(value[0])
    return `List[${inner}]`
  }
  if (typeof value === 'object') return 'dict'
  return 'str'
}

function generateDataclass(name: string, obj: Record<string, unknown>, classes: string[]): void {
  const fields: string[] = []
  const nestedClasses: string[] = []

  for (const [key, value] of Object.entries(obj)) {
    const fieldName = toSnakeCase(key)

    if (value === null || value === undefined) {
      fields.push(`    ${fieldName}: Optional[str] = None`)
    } else if (Array.isArray(value) && value.length > 0 && typeof value[0] === 'object' && value[0] !== null) {
      const nestedName = toClassName(key)
      generateDataclass(nestedName, value[0] as Record<string, unknown>, nestedClasses)
      fields.push(`    ${fieldName}: List[${nestedName}]`)
    } else if (typeof value === 'object' && !Array.isArray(value)) {
      const nestedName = toClassName(key)
      generateDataclass(nestedName, value as Record<string, unknown>, nestedClasses)
      fields.push(`    ${fieldName}: ${nestedName}`)
    } else {
      fields.push(`    ${fieldName}: ${pyType(value)}`)
    }
  }

  for (const nc of nestedClasses) {
    classes.push(nc)
  }

  const classStr = `@dataclass\nclass ${name}:\n${fields.length > 0 ? fields.join('\n') : '    pass'}`
  classes.push(classStr)
}

function needsImports(obj: Record<string, unknown>): { needsList: boolean; needsOptional: boolean } {
  let needsList = false
  let needsOptional = false

  for (const value of Object.values(obj)) {
    if (value === null || value === undefined) needsOptional = true
    if (Array.isArray(value)) needsList = true
    if (typeof value === 'object' && value !== null && !Array.isArray(value)) {
      const nested = needsImports(value as Record<string, unknown>)
      if (nested.needsList) needsList = true
      if (nested.needsOptional) needsOptional = true
    }
  }

  return { needsList, needsOptional }
}

export default function JsonToPythonTool() {
  const [input, setInput] = useState('')
  const [output, setOutput] = useState('')
  const [className, setClassName] = useState('AutoGenerated')
  const [error, setError] = useState('')

  const convert = () => {
    try {
      setError('')
      let parsed = JSON.parse(input)
      if (Array.isArray(parsed)) {
        if (parsed.length > 0 && typeof parsed[0] === 'object') {
          parsed = parsed[0]
        } else {
          setError('Input must be a JSON object or array of objects')
          setOutput('')
          return
        }
      }
      if (typeof parsed !== 'object' || parsed === null) {
        setError('Input must be a JSON object')
        setOutput('')
        return
      }

      const imports: string[] = ['from dataclasses import dataclass']
      const { needsList, needsOptional } = needsImports(parsed as Record<string, unknown>)
      const typingImports: string[] = []
      if (needsList) typingImports.push('List')
      if (needsOptional) typingImports.push('Optional')
      if (typingImports.length > 0) {
        imports.push(`from typing import ${typingImports.join(', ')}`)
      }

      const classes: string[] = []
      generateDataclass(className || 'AutoGenerated', parsed as Record<string, unknown>, classes)

      setOutput(imports.join('\n') + '\n\n\n' + classes.join('\n\n\n'))
    } catch (e) {
      setError(e instanceof Error ? e.message : 'Invalid JSON input')
      setOutput('')
    }
  }

  const clear = () => { setInput(''); setOutput(''); setError('') }

  return (
    <ToolPage title="JSON to Python Dataclass" description="Generate Python dataclass definitions from JSON with proper type annotations" category="developer" categoryLabel="Developer Tools"
      helpContent={
        <>
          <h2>What is This Tool?</h2>
          <p>JSON to Python Dict is a free browser-based tool that lets you convert JSON data into Python dictionary syntax with proper Python conventions (True/False/None instead of true/false/null). It processes everything locally in your browser using JavaScript, so your data never leaves your device. No sign-up, no installation, and no server uploads required — just open the tool and start using it immediately.</p>

          <h2>How to Use This Tool</h2>
          <ol>
            <li>Paste or type your code or data into the <strong>input panel</strong>.</li>
            <li>Select any formatting options or conversion targets if available.</li>
            <li>View the processed output instantly in the <strong>result panel</strong>.</li>
            <li>Use <strong>Copy</strong> to grab the output or <strong>Download</strong> to save it as a file.</li>
          </ol>

          <h2>When to Use This Tool</h2>
          <p>This tool is particularly useful when converting API response examples to Python code, creating test fixtures, or migrating data between JavaScript and Python. Since it runs entirely in your browser, it works offline after the page loads and keeps your data completely private. Whether you are a developer, designer, student, or professional, this Python development tool saves time and eliminates the need for desktop software installation.</p>

          <h2>Tips and Best Practices</h2>
          <ul>
            <li>For large inputs, the tool processes data efficiently in your browser but very large files may take a moment.</li>
            <li>Use keyboard shortcuts like Ctrl+A to select all output text before copying.</li>
            <li>The tool preserves your data types and structure during conversion or formatting.</li>
            <li>Compare the formatted output with the original to verify no data was altered.</li>
            <li>All processing is client-side — safe for use with proprietary or sensitive code.</li>
          </ul>
        </>
      }
 faqs={[
        { question: 'How do I convert JSON to Python dataclasses?', answer: 'Paste a JSON object into the input, set a class name, and click Generate to get Python dataclass definitions with proper type annotations and imports.' },
        { question: 'Does the tool generate Python type hints?', answer: 'Yes, all fields include type annotations such as str, int, float, bool, List[], and Optional[] based on the JSON values.' },
        { question: 'Are nested JSON objects supported?', answer: 'Yes, nested objects are converted into separate dataclass definitions with proper cross-references and snake_case field naming.' },
        { question: 'What Python imports are included?', answer: 'The tool automatically adds the dataclass import and any needed typing imports like List and Optional based on your JSON structure.' },
      ]}>
      <div className="mb-4">
        <label className="text-sm font-medium">Class Name</label>
        <input
          type="text"
          value={className}
          onChange={(e) => setClassName(e.target.value)}
          className="ml-2 px-3 py-1.5 rounded-md border border-input bg-tool-bg text-sm focus:outline-none focus:ring-2 focus:ring-ring"
          placeholder="AutoGenerated"
        />
      </div>
      <div className="grid grid-cols-1 lg:grid-cols-2 gap-4">
        <div>
          <div className="flex items-center justify-between mb-2">
            <span className="text-sm font-medium">JSON Input</span>
            <ClearButton onClear={clear} />
          </div>
          <ToolTextarea value={input} onChange={setInput} placeholder='{"name": "John", "age": 30, "is_active": true, "score": 9.5}' rows={14} />
        </div>
        <div>
          <div className="flex items-center justify-between mb-2">
            <span className="text-sm font-medium">Python Dataclass Output</span>
            <div className="flex gap-2">
              {output && <CopyButton text={output} />}
              {output && <DownloadButton content={output} filename="models.py" mimeType="text/plain" />}
            </div>
          </div>
          <ToolTextarea value={output} readOnly placeholder="Python dataclass will appear here..." rows={14} />
        </div>
      </div>
      {error && <div className="mt-3 p-3 rounded-lg bg-red-500/10 text-red-600 dark:text-red-400 text-sm font-mono">{error}</div>}
      <button onClick={convert} className="mt-4 px-4 py-2 rounded-lg bg-primary text-primary-foreground text-sm font-medium hover:bg-primary/90 transition-colors">
        Generate Python Dataclass
      </button>
    </ToolPage>
  )
}
