'use client'

import { useState } from 'react'
import { ToolPage, ToolTextarea, CopyButton, DownloadButton, ClearButton } from '@/components/tool-page'

function toPascalCase(str: string): string {
  return str
    .replace(/[^a-zA-Z0-9]/g, ' ')
    .split(/\s+/)
    .filter(Boolean)
    .map((w) => w.charAt(0).toUpperCase() + w.slice(1))
    .join('')
}

function goType(value: unknown): string {
  if (value === null || value === undefined) return 'interface{}'
  if (typeof value === 'boolean') return 'bool'
  if (typeof value === 'number') {
    return Number.isInteger(value) ? 'int' : 'float64'
  }
  if (typeof value === 'string') return 'string'
  if (Array.isArray(value)) {
    if (value.length === 0) return '[]interface{}'
    return '[]' + goType(value[0])
  }
  if (typeof value === 'object') return 'struct'
  return 'interface{}'
}

function generateStruct(name: string, obj: Record<string, unknown>, structs: string[]): string {
  const fields: string[] = []

  for (const [key, value] of Object.entries(obj)) {
    const fieldName = toPascalCase(key)
    let fieldType: string

    if (value === null || value === undefined) {
      fieldType = 'interface{}'
    } else if (Array.isArray(value)) {
      if (value.length > 0 && typeof value[0] === 'object' && value[0] !== null && !Array.isArray(value[0])) {
        const nestedName = toPascalCase(key)
        generateStruct(nestedName, value[0] as Record<string, unknown>, structs)
        fieldType = '[]' + nestedName
      } else if (value.length > 0) {
        fieldType = '[]' + goType(value[0])
      } else {
        fieldType = '[]interface{}'
      }
    } else if (typeof value === 'object') {
      const nestedName = toPascalCase(key)
      generateStruct(nestedName, value as Record<string, unknown>, structs)
      fieldType = nestedName
    } else {
      fieldType = goType(value)
    }

    fields.push(`\t${fieldName} ${fieldType} \`json:"${key}"\``)
  }

  const structStr = `type ${name} struct {\n${fields.join('\n')}\n}`
  structs.push(structStr)
  return structStr
}

export default function JsonToGoTool() {
  const [input, setInput] = useState('')
  const [output, setOutput] = useState('')
  const [structName, setStructName] = useState('AutoGenerated')
  const [error, setError] = useState('')

  const convert = () => {
    try {
      setError('')
      const parsed = JSON.parse(input)
      if (typeof parsed !== 'object' || parsed === null || Array.isArray(parsed)) {
        if (Array.isArray(parsed) && parsed.length > 0 && typeof parsed[0] === 'object') {
          const structs: string[] = []
          generateStruct(structName || 'AutoGenerated', parsed[0] as Record<string, unknown>, structs)
          setOutput(structs.reverse().join('\n\n'))
          return
        }
        setError('Input must be a JSON object or array of objects')
        setOutput('')
        return
      }
      const structs: string[] = []
      generateStruct(structName || 'AutoGenerated', parsed as Record<string, unknown>, structs)
      setOutput(structs.reverse().join('\n\n'))
    } catch (e) {
      setError(e instanceof Error ? e.message : 'Invalid JSON input')
      setOutput('')
    }
  }

  const clear = () => { setInput(''); setOutput(''); setError('') }

  return (
    <ToolPage title="JSON to Go Struct" description="Generate Go struct definitions from JSON data with proper types and json tags" category="developer" categoryLabel="Developer Tools">
      <div className="mb-4">
        <label className="text-sm font-medium">Struct Name</label>
        <input
          type="text"
          value={structName}
          onChange={(e) => setStructName(e.target.value)}
          className="ml-2 px-3 py-1.5 rounded-md border border-input bg-tool-bg text-sm focus:outline-none focus:ring-2 focus:ring-ring"
          placeholder="AutoGenerated"
        />
      </div>
      <div className="grid grid-cols-1 lg:grid-cols-2 gap-4">
        <div>
          <div className="flex items-center justify-between mb-2">
            <span className="text-sm font-medium">JSON Input</span>
            <ClearButton onClear={clear} />
          </div>
          <ToolTextarea value={input} onChange={setInput} placeholder='{"name": "John", "age": 30, "is_active": true, "score": 9.5}' rows={14} />
        </div>
        <div>
          <div className="flex items-center justify-between mb-2">
            <span className="text-sm font-medium">Go Struct Output</span>
            <div className="flex gap-2">
              {output && <CopyButton text={output} />}
              {output && <DownloadButton content={output} filename="types.go" mimeType="text/plain" />}
            </div>
          </div>
          <ToolTextarea value={output} readOnly placeholder="Go struct will appear here..." rows={14} />
        </div>
      </div>
      {error && <div className="mt-3 p-3 rounded-lg bg-red-500/10 text-red-600 dark:text-red-400 text-sm font-mono">{error}</div>}
      <button onClick={convert} className="mt-4 px-4 py-2 rounded-lg bg-primary text-primary-foreground text-sm font-medium hover:bg-primary/90 transition-colors">
        Generate Go Struct
      </button>
    </ToolPage>
  )
}
